### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by dngray** [maxlath/backup-github-repo#6]
Hi,

Even with an apikey I'm finding this is still being rate limited. We have 2277 issues. After 559 the rest are rate limited without data.

> "message": "API rate limit exceeded for user ID XXXXXXXX."

I think GitHub only allows 5000 requests per hour, it would be awesome if this script could do some rate limiting.

Something else I noticed is the /html directory, most of the repos i checked out would only create 9 html files. In this case for our 2277 issues we got 0999.html was the last file. Could this be something to do with rate limiting?

**Comment by maxlath** [comment]
The problem with rate limiting is that an instance of the process can't know if another process already consumed part of the quota, so I would like to try another approach: retry on request error with an increasing delay of up to 20min 01b9dd0 
Could you try to see if that fixes your issue?

The issue on the html files should have been fixed by 9ba5942

btw, as of this morning, there is a new installation option via npm: `npm install -g backup-github-repo`

**Comment by jonaharagon** [comment]
I'm able to check my remaining API calls with `curl -I https://api.github.com/users/jonaharagon/orgs -u my_client_id:<TOKEN>`, would this not work?

**Comment by maxlath** [comment]
@jonaharagon oh nice! ^^
I made an attempt to take those headers into account in b0caf1d and published it in `v1.1.0`

**Comment by jonaharagon** [comment]
Well it took an hour longer of course, but this worked perfectly for me. Thanks for the update!!
